apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  #namespace: api
spec:
  selector:
    matchLabels:
      run: trips
  replicas: 1
  template:
    metadata:
      labels:
        run: trips
    spec:
      containers:
      - name: trips
        image: registryhwt0547.azurecr.io/tripinsights/trips:1.0
        volumeMounts:
        - name: trips-kv
          mountPath: /secrets
          readOnly: true
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: OPENAPI_DOCS_URI
          value: http://localhost
      volumes:
      - name: trips-kv
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds
          options:
            usepodidentity: "false"
            keyvaultname: "team4keyvault"
            keyvaultobjectnames: SQL-USER;SQL-PASSWORD;SQL-FDQN
            keyvaultobjecttypes: secret;secret;secret
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER"
            resourcegroup: "teamResources"
            subscriptionid: "4135126c-0362-4eb3-94f0-105cf7f8b9a9"
            tenantid: "10ac67db-0119-433f-9e55-b72bb9b81830"
---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
  #namespace: api
  labels:
    run: trips
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: trips
