apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer2-deployment
  namespace: web
spec:
  selector:
    matchLabels:
      run: tripviewer2
  replicas: 1
  template:
    metadata:
      labels:
        run: tripviewer2

    spec:
      containers:
      - name: tripviewer2
        image: registryhwt0547.azurecr.io/tripviewer2:2.0
        ports:
        - containerPort: 80
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: 'http://userprofile-service.api'
          - name: TRIPS_API_ENDPOINT
            value: 'http://trips-service.api'
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: WCF_ENDPOINT
            value: 'http://wcf-service.api'
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer2-service
  namespace: web
  labels:
    run: tripviewer2
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: tripviewer2
  
